#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Interactive .env builder for TBR Sync Bot.

Run directly (`python3 setup_env.py`) or through `tbrctl config`.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

ENV_PATH = Path(__file__).resolve().parent / ".env"

C_RESET = "\033[0m"
C_BOLD = "\033[1m"
C_DIM = "\033[2m"
C_GREEN = "\033[32m"
C_YELLOW = "\033[33m"
C_RED = "\033[31m"


def color(text: str, code: str) -> str:
    return text if os.environ.get("NO_COLOR") else f"{code}{text}{C_RESET}"


def read_existing() -> dict[str, str]:
    values: dict[str, str] = {}
    if not ENV_PATH.exists():
        return values
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()
    return values


def ask(prompt: str, current: str | None = None, secret: bool = False, required: bool = True) -> str:
    shown = ""
    if current:
        shown = f" [{'*' * 8 if secret else current}]"
    while True:
        try:
            answer = input(color(f"{prompt}{shown}: ", C_BOLD)).strip()
        except EOFError:
            print()
            sys.exit(color("\nCancelled: no input available (run this in an interactive terminal).", C_RED))
        if not answer and current:
            return current
        if answer:
            return answer
        if not required:
            return ""
        print(color("  This value is required.", C_YELLOW))


def ask_bool(prompt: str, current: str | None, default: bool) -> str:
    current_bool = default
    if current is not None:
        current_bool = current.strip().lower() in {"1", "true", "yes", "y", "on"}
    hint = "Y/n" if current_bool else "y/N"
    try:
        answer = input(color(f"{prompt} [{hint}]: ", C_BOLD)).strip().lower()
    except EOFError:
        answer = ""
    if not answer:
        return "true" if current_bool else "false"
    return "true" if answer in {"y", "yes", "1", "true", "on"} else "false"


def normalize_channel(value: str) -> str:
    value = value.strip()
    # A numeric id is valid as-is; a name needs the @ prefix.
    if value.startswith("@") or value.lstrip("-").isdigit():
        return value
    return "@" + value


def main() -> None:
    print()
    print(color("TBR Sync Bot — configuration", C_BOLD))
    print(color("Press Enter to keep the value shown in brackets.", C_DIM))
    print()

    existing = read_existing()
    if existing:
        print(color(f"Existing {ENV_PATH.name} found; values will be updated.", C_DIM))
        print()

    values: dict[str, str] = {}
    values["bale_token"] = ask("Bale bot token", existing.get("bale_token"), secret=True)
    values["telegram_token"] = ask("Telegram bot token", existing.get("telegram_token"), secret=True)
    values["bale_channel_id"] = normalize_channel(
        ask("Bale source channel (@name or numeric id)", existing.get("bale_channel_id"))
    )
    values["telegram_channel_id"] = normalize_channel(
        ask("Telegram destination channel (@name or numeric id)", existing.get("telegram_channel_id"))
    )

    print()
    print(color("Optional settings", C_BOLD))
    values["force_rtl"] = ask_bool("Force right-to-left marks on each line?", existing.get("force_rtl"), False)
    values["sync_old_messages"] = ask_bool(
        "Process posts that were queued while the bot was offline?", existing.get("sync_old_messages"), False
    )
    values["max_file_mb"] = ask(
        "Maximum file size to forward, in MB (Telegram bots cap at 50)", existing.get("max_file_mb") or "45"
    )
    old_user = ask(
        "Bale username to rewrite in text (leave empty to skip)", existing.get("bale_username_to_replace"), required=False
    )
    if old_user:
        values["bale_username_to_replace"] = old_user
        values["telegram_username_replacement"] = ask(
            "Replace it with", existing.get("telegram_username_replacement")
        )

    # Preserve any advanced keys the user set by hand.
    for key, value in existing.items():
        values.setdefault(key, value)

    lines = [
        "# TBR Sync Bot configuration",
        "# Generated by setup_env.py — safe to edit by hand.",
        "",
        "# --- required ---",
        f"bale_token={values['bale_token']}",
        f"telegram_token={values['telegram_token']}",
        f"bale_channel_id={values['bale_channel_id']}",
        f"telegram_channel_id={values['telegram_channel_id']}",
        "",
        "# --- optional ---",
    ]
    for key in sorted(k for k in values if k not in {"bale_token", "telegram_token", "bale_channel_id", "telegram_channel_id"}):
        lines.append(f"{key}={values[key]}")
    lines.append("")

    ENV_PATH.write_text("\n".join(lines), encoding="utf-8")
    try:
        ENV_PATH.chmod(0o600)
    except OSError:
        pass

    print()
    print(color(f"✔ Wrote {ENV_PATH}", C_GREEN))
    print(color("  File permissions set to 600 — it holds your bot tokens, keep it out of git.", C_DIM))
    print()


if __name__ == "__main__":
    main()
